os: linux
dist: xenial
language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  EXTNAME: tinyexpr

jobs:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis
  - /^v\d+\.\d+\.\d+$/

install:
  - phpize
  - ./configure --enable-tinyexpr
  - make

before_script:
  make install

script:
  - php -m
  - make test

after_failure:
  - |
    for FILE in $(find tests -name '*.diff'); do
      echo $FILE
      cat FILE
      echo
    done

before_deploy:
  - pecl package
  - export RELEASE_PACKAGE=$(ls "$EXTNAME"-*.tgz)

deploy:
  provider: releases
  # auth_token:
  #   secure: <your encrypted token>
  file: "$RELEASE_PACKAGE"
  cleanup: false
  name: "$TRAVIS_TAG"
  prerelease: true
  on:
    tags: true
